server:
  port: 12001
  max-http-header-size: 10240
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: au-user
  datasource:
    url: jdbc:mysql://localhost:3306/au-db?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: admin
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 9
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN

auth-server: http://localhost:12002
security:
  oauth2:
    client:
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
      client-id: au-oauth
      client-secret: 123456
      grant-type: password
      scope: read
    resource:
      tokenType: Bearer
      id: ${spring.application.name}
      token-info-uri: ${auth-server}/oauth/check_token
      user-info-uri: ${auth-server}/user/principal
      prefer-token-info: false


logging:
  config: classpath:logback-spring.xml

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      table-underline: true
    enable-sql-runner: true
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE